'use client';

import { ProjectStoreProvider } from '@/app/stores/project-store-provider';
import Header from '@/app/components/Header';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };
import '@/app/ui/global.css';

export default function ProjectLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ProjectStoreProvider>
      <h1>project layout</h1>
      <Header />
      {children}
    </ProjectStoreProvider>
  );
}
